version: 2
jobs:
  build:
    working_directory: ~/DemoThundra
    docker:
      - image: microsoft/dotnet:2-sdk
        
    steps:
      - checkout
      - run: cd test/DemoThundra.Tests/  && dotnet test